/**
 * Auto-generated by MCPForge Agent Demo
 * Run: npx tsx start-task-manager-api.ts
 */
import { createMcpHttpServer } from './src/protocol/http-server.js';
import { McpRuntimeServer } from './src/protocol/server.js';
import { ServerConfigSchema } from './src/schema.js';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(fs.readFileSync(path.join(__dirname, 'task-manager-api.config.json'), 'utf8'));
const config = ServerConfigSchema.parse(raw);
const PORT = Number(process.env.PORT) || 3001;
process.env.ALLOW_LOOPBACK_DEV = '1';

const runtime = new McpRuntimeServer(config);
const server = createMcpHttpServer(runtime);
server.listen(PORT, '127.0.0.1', () => {
  console.log('\n✅  task-manager-api MCP Server running!');
  console.log(`🌐  Studio UI : http://127.0.0.1:${PORT}/studio`);
  console.log(`📡  MCP URL   : http://127.0.0.1:${PORT}/mcp`);
  console.log(`🔑  API Key   : (set X-API-Key header)\n`);
  console.log('Tools:');
  config.tools.forEach(t => console.log(`  ${t.enabled !== false ? '🟢' : '🔴'} ${t.name}`));
});
